# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.marker_dto import MarkerDTO

class TestMarkerDTO(unittest.TestCase):
    """MarkerDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarkerDTO:
        """Test MarkerDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarkerDTO`
        """
        model = MarkerDTO()
        if include_optional:
            return MarkerDTO(
                id = '',
                name = 'awat5ikwowtta-3mh2lcafqw3zhes',
                type = 'dataset',
                title = '0',
                description = '',
                content = cm_python_openapi_sdk.models.marker_content_dto.MarkerContentDTO(
                    style = 'q', 
                    property_filters = [
                        null
                        ], )
            )
        else:
            return MarkerDTO(
                name = 'awat5ikwowtta-3mh2lcafqw3zhes',
                title = '0',
                content = cm_python_openapi_sdk.models.marker_content_dto.MarkerContentDTO(
                    style = 'q', 
                    property_filters = [
                        null
                        ], ),
        )
        """

    def testMarkerDTO(self):
        """Test MarkerDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
