# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.update_project_dto import UpdateProjectDTO

class TestUpdateProjectDTO(unittest.TestCase):
    """UpdateProjectDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateProjectDTO:
        """Test UpdateProjectDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateProjectDTO`
        """
        model = UpdateProjectDTO()
        if include_optional:
            return UpdateProjectDTO(
                title = '0',
                description = '',
                organization_id = 'w8q6zgckec0l3o4g',
                status = 'ENABLED',
                services = None
            )
        else:
            return UpdateProjectDTO(
        )
        """

    def testUpdateProjectDTO(self):
        """Test UpdateProjectDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
