# coding: utf-8

"""
    clevermaps-client

    CleverMaps REST API provides access to location intelligence and geospatial analytics platform.  ### Main capabilities include: - Project and user access management - Multidimensional data model and metrics management - Data upload and exports - Ad-hoc analysis of geospatial data - Full text and geographic search - Configuration of CleverMaps Studio visualizations 

    The version of the OpenAPI document: 1.0.0
    Contact: support@clevermaps.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.api.maps_api import MapsApi


class TestMapsApi(unittest.TestCase):
    """MapsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MapsApi()

    def tearDown(self) -> None:
        pass

    def test_create_map(self) -> None:
        """Test case for create_map

        Creates new Map.
        """
        pass

    def test_delete_map_by_id(self) -> None:
        """Test case for delete_map_by_id

        Deletes map by id
        """
        pass

    def test_get_all_maps(self) -> None:
        """Test case for get_all_maps

        Returns paged collection of all Maps in a project.
        """
        pass

    def test_get_map_by_id(self) -> None:
        """Test case for get_map_by_id

        Gets map by id
        """
        pass

    def test_get_map_by_name(self) -> None:
        """Test case for get_map_by_name

        Gets map by name
        """
        pass

    def test_update_map_by_id(self) -> None:
        """Test case for update_map_by_id

        Updates map by id
        """
        pass


if __name__ == '__main__':
    unittest.main()
