# coding: utf-8

"""
    clevermaps-client

    CleverMaps REST API provides access to location intelligence and geospatial analytics platform.  ### Main capabilities include: - Project and user access management - Multidimensional data model and metrics management - Data upload and exports - Ad-hoc analysis of geospatial data - Full text and geographic search - Configuration of CleverMaps Studio visualizations 

    The version of the OpenAPI document: 1.0.0
    Contact: support@clevermaps.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.bulk_point_query_request import BulkPointQueryRequest

class TestBulkPointQueryRequest(unittest.TestCase):
    """BulkPointQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkPointQueryRequest:
        """Test BulkPointQueryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkPointQueryRequest`
        """
        model = BulkPointQueryRequest()
        if include_optional:
            return BulkPointQueryRequest(
                enable_billing = True,
                points = [
                    cm_python_openapi_sdk.models.bulk_point_query_request_points_inner.BulkPointQueryRequest_points_inner(
                        id = '', 
                        lat = 1.337, 
                        lng = 1.337, )
                    ],
                point_queries = [
                    null
                    ]
            )
        else:
            return BulkPointQueryRequest(
                points = [
                    cm_python_openapi_sdk.models.bulk_point_query_request_points_inner.BulkPointQueryRequest_points_inner(
                        id = '', 
                        lat = 1.337, 
                        lng = 1.337, )
                    ],
                point_queries = [
                    null
                    ],
        )
        """

    def testBulkPointQueryRequest(self):
        """Test BulkPointQueryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
