# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.function_h3_grid import FunctionH3Grid

class TestFunctionH3Grid(unittest.TestCase):
    """FunctionH3Grid unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FunctionH3Grid:
        """Test FunctionH3Grid
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FunctionH3Grid`
        """
        model = FunctionH3Grid()
        if include_optional:
            return FunctionH3Grid(
                id = 'z0',
                type = 'function_h3_grid',
                options = cm_python_openapi_sdk.models.function_h3_grid_options.FunctionH3Grid_options(
                    dataset = 'awat5ikwowtta-3mh2lcafqw3zhes', 
                    resolution = 0, )
            )
        else:
            return FunctionH3Grid(
                type = 'function_h3_grid',
                options = cm_python_openapi_sdk.models.function_h3_grid_options.FunctionH3Grid_options(
                    dataset = 'awat5ikwowtta-3mh2lcafqw3zhes', 
                    resolution = 0, ),
        )
        """

    def testFunctionH3Grid(self):
        """Test FunctionH3Grid"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
