# coding: utf-8

"""
    clevermaps-client

    CleverMaps REST API provides access to location intelligence and geospatial analytics platform.  ### Main capabilities include: - Project and user access management - Multidimensional data model and metrics management - Data upload and exports - Ad-hoc analysis of geospatial data - Full text and geographic search - Configuration of CleverMaps Studio visualizations 

    The version of the OpenAPI document: 1.0.0
    Contact: support@clevermaps.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.project_settings_content_dto import ProjectSettingsContentDTO

class TestProjectSettingsContentDTO(unittest.TestCase):
    """ProjectSettingsContentDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectSettingsContentDTO:
        """Test ProjectSettingsContentDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectSettingsContentDTO`
        """
        model = ProjectSettingsContentDTO()
        if include_optional:
            return ProjectSettingsContentDTO(
                geo_search_countries = [
                    'AE'
                    ],
                geo_search_providers = [
                    'Mapbox'
                    ],
                project_template = {templateDatasets=[{dataset=dataset}, {dataset=dataset}]},
                trusted_origins = [
                    ''
                    ],
                allow_unsecured_origins = True,
                default_views = [
                    '/rest/projects/8q6zgckec0l3o4gi/md/views?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc'
                    ]
            )
        else:
            return ProjectSettingsContentDTO(
                geo_search_providers = [
                    'Mapbox'
                    ],
        )
        """

    def testProjectSettingsContentDTO(self):
        """Test ProjectSettingsContentDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
