# coding: utf-8

"""
    clevermaps-client

    CleverMaps REST API provides access to location intelligence and geospatial analytics platform.  ### Main capabilities include: - Project and user access management - Multidimensional data model and metrics management - Data upload and exports - Ad-hoc analysis of geospatial data - Full text and geographic search - Configuration of CleverMaps Studio visualizations 

    The version of the OpenAPI document: 1.0.0
    Contact: support@clevermaps.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.bulk_point_query_request_point_queries_isochrone import BulkPointQueryRequestPointQueriesIsochrone

class TestBulkPointQueryRequestPointQueriesIsochrone(unittest.TestCase):
    """BulkPointQueryRequestPointQueriesIsochrone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkPointQueryRequestPointQueriesIsochrone:
        """Test BulkPointQueryRequestPointQueriesIsochrone
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkPointQueryRequestPointQueriesIsochrone`
        """
        model = BulkPointQueryRequestPointQueriesIsochrone()
        if include_optional:
            return BulkPointQueryRequestPointQueriesIsochrone(
                query_id = '',
                type = 'isochrone',
                options = cm_python_openapi_sdk.models.bulk_point_query_request_point_queries_isochrone_options.BulkPointQueryRequestPointQueriesIsochrone_options(
                    profile = 'car', 
                    unit = 'time', 
                    amount = 1, ),
                dataset = '',
                execution_content = cm_python_openapi_sdk.models.execution_content.executionContent(),
                properties = [
                    None
                    ],
                filter_by = [
                    None
                    ],
                result_set_filter = [
                    None
                    ],
                having = [
                    None
                    ],
                order_by = [
                    None
                    ],
                variables = [
                    None
                    ],
                limit = 56
            )
        else:
            return BulkPointQueryRequestPointQueriesIsochrone(
                type = 'isochrone',
                options = cm_python_openapi_sdk.models.bulk_point_query_request_point_queries_isochrone_options.BulkPointQueryRequestPointQueriesIsochrone_options(
                    profile = 'car', 
                    unit = 'time', 
                    amount = 1, ),
                dataset = '',
        )
        """

    def testBulkPointQueryRequestPointQueriesIsochrone(self):
        """Test BulkPointQueryRequestPointQueriesIsochrone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
