# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.get_project_members200_response import GetProjectMembers200Response

class TestGetProjectMembers200Response(unittest.TestCase):
    """GetProjectMembers200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProjectMembers200Response:
        """Test GetProjectMembers200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProjectMembers200Response`
        """
        model = GetProjectMembers200Response()
        if include_optional:
            return GetProjectMembers200Response(
                links = [
                    None
                    ],
                content = [
                    cm_python_openapi_sdk.models.membership_dto.MembershipDTO(
                        id = '', 
                        account_id = '', 
                        status = 'ENABLED', 
                        role = 'ANONYMOUS', 
                        created_at = '', 
                        modified_at = '', 
                        account = cm_python_openapi_sdk.models.account.account(), 
                        links = [
                            None
                            ], )
                    ],
                page = cm_python_openapi_sdk.models.mandatory_keys_for_pagable_response.mandatory keys for pagable response(
                    size = 56, 
                    total_elements = null, 
                    total_pages = 56, 
                    number = 56, ),
                id = '',
                account_id = '',
                status = 'ENABLED',
                role = 'ANONYMOUS',
                created_at = '',
                modified_at = '',
                account = cm_python_openapi_sdk.models.account.account()
            )
        else:
            return GetProjectMembers200Response(
                status = 'ENABLED',
                role = 'ANONYMOUS',
        )
        """

    def testGetProjectMembers200Response(self):
        """Test GetProjectMembers200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
