# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.project_settings_dto import ProjectSettingsDTO

class TestProjectSettingsDTO(unittest.TestCase):
    """ProjectSettingsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectSettingsDTO:
        """Test ProjectSettingsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectSettingsDTO`
        """
        model = ProjectSettingsDTO()
        if include_optional:
            return ProjectSettingsDTO(
                id = '',
                name = 'awat5ikwowtta-3mh2lcafqw3zhes',
                type = 'dataset',
                title = '0',
                description = '0',
                content = cm_python_openapi_sdk.models.project_settings_content_dto.ProjectSettingsContentDTO(
                    geo_search_countries = [
                        'AE'
                        ], 
                    geo_search_providers = [
                        'Mapbox'
                        ], 
                    project_template = cm_python_openapi_sdk.models.project_template_dto.ProjectTemplateDTO(
                        template_datasets = [
                            cm_python_openapi_sdk.models.template_dataset_dto.TemplateDatasetDTO(
                                dataset = '/rest/projects/8q6zgckec0l3o4gi/md/datasets?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc', )
                            ], ), 
                    trusted_origins = [
                        ''
                        ], 
                    allow_unsecured_origins = True, 
                    default_views = [
                        '/rest/projects/8q6zgckec0l3o4gi/md/views?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc'
                        ], )
            )
        else:
            return ProjectSettingsDTO(
                name = 'awat5ikwowtta-3mh2lcafqw3zhes',
                content = cm_python_openapi_sdk.models.project_settings_content_dto.ProjectSettingsContentDTO(
                    geo_search_countries = [
                        'AE'
                        ], 
                    geo_search_providers = [
                        'Mapbox'
                        ], 
                    project_template = cm_python_openapi_sdk.models.project_template_dto.ProjectTemplateDTO(
                        template_datasets = [
                            cm_python_openapi_sdk.models.template_dataset_dto.TemplateDatasetDTO(
                                dataset = '/rest/projects/8q6zgckec0l3o4gi/md/datasets?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc', )
                            ], ), 
                    trusted_origins = [
                        ''
                        ], 
                    allow_unsecured_origins = True, 
                    default_views = [
                        '/rest/projects/8q6zgckec0l3o4gi/md/views?name=lcafqw3zheseh16mckwqaot6282x4vh6wt7cgd04d0gu12zwv6v61pi05te5cj19uo1-vud_-tc_vbqgp4vj0u4t9xwduicwsc'
                        ], ),
        )
        """

    def testProjectSettingsDTO(self):
        """Test ProjectSettingsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
