# coding: utf-8

"""
    clevermaps-client

    CleverMaps REST API provides access to location intelligence and geospatial analytics platform.  ### Main capabilities include: - Project and user access management - Multidimensional data model and metrics management - Data upload and exports - Ad-hoc analysis of geospatial data - Full text and geographic search - Configuration of CleverMaps Studio visualizations 

    The version of the OpenAPI document: 1.0.0
    Contact: support@clevermaps.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.api.accounts_api import AccountsApi


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountsApi()

    def tearDown(self) -> None:
        pass

    def test_change_onboarding(self) -> None:
        """Test case for change_onboarding

        Change account onboarding
        """
        pass

    def test_change_password(self) -> None:
        """Test case for change_password

        Change password
        """
        pass

    def test_change_preferences(self) -> None:
        """Test case for change_preferences

        Change account preferences
        """
        pass

    def test_delete_account_by_id(self) -> None:
        """Test case for delete_account_by_id

        Delete account.
        """
        pass

    def test_get_account_by_account_id(self) -> None:
        """Test case for get_account_by_account_id

        Get account by accountId
        """
        pass

    def test_get_account_by_email(self) -> None:
        """Test case for get_account_by_email

        Find if account with email exists.
        """
        pass

    def test_get_current_account(self) -> None:
        """Test case for get_current_account

        Get current account.
        """
        pass

    def test_register_account(self) -> None:
        """Test case for register_account

        Register new account
        """
        pass


if __name__ == '__main__':
    unittest.main()
