# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.api.project_invitations_api import ProjectInvitationsApi


class TestProjectInvitationsApi(unittest.TestCase):
    """ProjectInvitationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectInvitationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_invitation(self) -> None:
        """Test case for create_invitation

        Create new invitation to the project for a user.
        """
        pass

    def test_delete_invitation(self) -> None:
        """Test case for delete_invitation

        Delete invitation.
        """
        pass

    def test_get_invitation_by_id(self) -> None:
        """Test case for get_invitation_by_id

        Get detail of an invitation.
        """
        pass

    def test_get_invitations(self) -> None:
        """Test case for get_invitations

        Get list of project invitations.
        """
        pass

    def test_update_invitation(self) -> None:
        """Test case for update_invitation

        Update invitation.
        """
        pass


if __name__ == '__main__':
    unittest.main()
