# coding: utf-8

"""
    clevermaps-client

    CleverMaps REST API provides access to location intelligence and geospatial analytics platform.  ### Main capabilities include: - Project and user access management - Multidimensional data model and metrics management - Data upload and exports - Ad-hoc analysis of geospatial data - Full text and geographic search - Configuration of CleverMaps Studio visualizations 

    The version of the OpenAPI document: 1.0.0
    Contact: support@clevermaps.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.general_job_request import GeneralJobRequest

class TestGeneralJobRequest(unittest.TestCase):
    """GeneralJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeneralJobRequest:
        """Test GeneralJobRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeneralJobRequest`
        """
        model = GeneralJobRequest()
        if include_optional:
            return GeneralJobRequest(
                type = 'E',
                project_id = 'w8q6zgckec0l3o4g',
                content = cm_python_openapi_sdk.models.import_project_request.ImportProjectRequest(
                    force = True, 
                    source_project_id = '', 
                    cascade_from = '', 
                    prefix = '', 
                    attribute_styles = True, 
                    dashboard = True, 
                    data_permissions = True, 
                    datasets = True, 
                    exports = True, 
                    indicators = True, 
                    indicator_drills = True, 
                    maps = True, 
                    markers = True, 
                    marker_selectors = True, 
                    metrics = True, 
                    project_settings = True, 
                    views = True, 
                    skip_data = True, )
            )
        else:
            return GeneralJobRequest(
                type = 'E',
                project_id = 'w8q6zgckec0l3o4g',
                content = cm_python_openapi_sdk.models.import_project_request.ImportProjectRequest(
                    force = True, 
                    source_project_id = '', 
                    cascade_from = '', 
                    prefix = '', 
                    attribute_styles = True, 
                    dashboard = True, 
                    data_permissions = True, 
                    datasets = True, 
                    exports = True, 
                    indicators = True, 
                    indicator_drills = True, 
                    maps = True, 
                    markers = True, 
                    marker_selectors = True, 
                    metrics = True, 
                    project_settings = True, 
                    views = True, 
                    skip_data = True, ),
        )
        """

    def testGeneralJobRequest(self):
        """Test GeneralJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
