# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.organization_paged_model_dto import OrganizationPagedModelDTO

class TestOrganizationPagedModelDTO(unittest.TestCase):
    """OrganizationPagedModelDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationPagedModelDTO:
        """Test OrganizationPagedModelDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationPagedModelDTO`
        """
        model = OrganizationPagedModelDTO()
        if include_optional:
            return OrganizationPagedModelDTO(
                links = [
                    None
                    ],
                content = [
                    cm_python_openapi_sdk.models.organization_response_dto.OrganizationResponseDTO(
                        id = 'w8q6zgckec0l3o4g', 
                        title = '0', 
                        invitation_email = '', 
                        dwh_cluster_id = 'w8q6zg', 
                        created_at = '', 
                        modified_at = '', 
                        links = [
                            None
                            ], )
                    ],
                page = cm_python_openapi_sdk.models.mandatory_keys_for_pagable_response.mandatory keys for pagable response(
                    size = 56, 
                    total_elements = null, 
                    total_pages = 56, 
                    number = 56, )
            )
        else:
            return OrganizationPagedModelDTO(
        )
        """

    def testOrganizationPagedModelDTO(self):
        """Test OrganizationPagedModelDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
