# coding: utf-8

"""
    clevermaps-client

    CleverMaps REST API provides access to location intelligence and geospatial analytics platform.  ### Main capabilities include: - Project and user access management - Multidimensional data model and metrics management - Data upload and exports - Ad-hoc analysis of geospatial data - Full text and geographic search - Configuration of CleverMaps Studio visualizations 

    The version of the OpenAPI document: 1.0.0
    Contact: support@clevermaps.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.dwh_query_request2 import DwhQueryRequest2

class TestDwhQueryRequest2(unittest.TestCase):
    """DwhQueryRequest2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DwhQueryRequest2:
        """Test DwhQueryRequest2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DwhQueryRequest2`
        """
        model = DwhQueryRequest2()
        if include_optional:
            return DwhQueryRequest2(
                execution_context = None,
                properties = [
                    null
                    ],
                filter_by = [
                    null
                    ],
                having = [
                    null
                    ],
                result_set_filter = [
                    null
                    ],
                order_by = [
                    cm_python_openapi_sdk.models.order_by.OrderBy(
                        property = null, 
                        property_id = 'z0', 
                        direction = 'asc', 
                        nulls = 'last', )
                    ],
                variables = [
                    cm_python_openapi_sdk.models.variable_value.VariableValue(
                        variable = 'awat5ikwowtta-3mh2lcafqw3zhes', 
                        value = 1.337, )
                    ],
                limit = 1
            )
        else:
            return DwhQueryRequest2(
                properties = [
                    null
                    ],
        )
        """

    def testDwhQueryRequest2(self):
        """Test DwhQueryRequest2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
