# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.api.user_invitations_api import UserInvitationsApi


class TestUserInvitationsApi(unittest.TestCase):
    """UserInvitationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserInvitationsApi()

    def tearDown(self) -> None:
        pass

    def test_accept_user_invitation(self) -> None:
        """Test case for accept_user_invitation

        Accept invitation.
        """
        pass

    def test_get_user_invitation(self) -> None:
        """Test case for get_user_invitation

        Get detail of an invitation.
        """
        pass


if __name__ == '__main__':
    unittest.main()
