# coding: utf-8

"""
    clevermaps-client

    CleverMaps REST API provides access to location intelligence and geospatial analytics platform.  ### Main capabilities include: - Project and user access management - Multidimensional data model and metrics management - Data upload and exports - Ad-hoc analysis of geospatial data - Full text and geographic search - Configuration of CleverMaps Studio visualizations 

    The version of the OpenAPI document: 1.0.0
    Contact: support@clevermaps.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.project_response_dto import ProjectResponseDTO

class TestProjectResponseDTO(unittest.TestCase):
    """ProjectResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectResponseDTO:
        """Test ProjectResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectResponseDTO`
        """
        model = ProjectResponseDTO()
        if include_optional:
            return ProjectResponseDTO(
                id = 'w8q6zgckec0l3o4g',
                title = '0',
                description = '',
                organization_id = 'w8q6zgckec0l3o4g',
                status = 'ENABLED',
                share = 'PRIVATE',
                created_at = '',
                modified_at = '',
                membership = {accountId=accountId, createdAt=createdAt, role=ANONYMOUS, modifiedAt=modifiedAt, links=[{}, {}], id=id, account={preferences={sendNewsletter=true, lastActiveOrganization=lastActiveOrganization, language=language, lastActiveProject=lastActiveProject}, phoneNumber=phoneNumber, requireAdditionalAttributes=true, fullName=fullName, anonymous=true, onboarding={introShown=[introShown, introShown], tipsShown=[tipsShown, tipsShown]}, links=[{}, {}], id=id, consentGranted=true, jobInfo={companyName=companyName, industry=industry, jobPosition=jobPosition}, email=email, status=ENABLED}, status=ENABLED},
                services = None,
                links = [
                    None
                    ]
            )
        else:
            return ProjectResponseDTO(
                id = 'w8q6zgckec0l3o4g',
                title = '0',
                organization_id = 'w8q6zgckec0l3o4g',
                status = 'ENABLED',
                share = 'PRIVATE',
                created_at = '',
                links = [
                    None
                    ],
        )
        """

    def testProjectResponseDTO(self):
        """Test ProjectResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
