# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_create_project(self) -> None:
        """Test case for create_project

        Create new project
        """
        pass

    def test_delete_project(self) -> None:
        """Test case for delete_project

        Delete project.
        """
        pass

    def test_get_all_projects(self) -> None:
        """Test case for get_all_projects

        Get list of projects for authenticated account.
        """
        pass

    def test_get_project_by_id(self) -> None:
        """Test case for get_project_by_id

        Get project by given project id.
        """
        pass

    def test_update_project(self) -> None:
        """Test case for update_project

        Update the project.
        """
        pass


if __name__ == '__main__':
    unittest.main()
