# coding: utf-8

"""
    clevermaps-client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.display_options_dto import DisplayOptionsDTO

class TestDisplayOptionsDTO(unittest.TestCase):
    """DisplayOptionsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DisplayOptionsDTO:
        """Test DisplayOptionsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DisplayOptionsDTO`
        """
        model = DisplayOptionsDTO()
        if include_optional:
            return DisplayOptionsDTO(
                value_options = [
                    cm_python_openapi_sdk.models.value_option_dto.ValueOptionDTO(
                        value = null, 
                        color = 'purple', 
                        hex_color = '0123456', 
                        weight = 1.337, 
                        pattern = 'solid', )
                    ]
            )
        else:
            return DisplayOptionsDTO(
        )
        """

    def testDisplayOptionsDTO(self):
        """Test DisplayOptionsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
