# coding: utf-8

"""
    clevermaps-client

    CleverMaps REST API provides access to location intelligence and geospatial analytics platform.  ### Main capabilities include: - Project and user access management - Multidimensional data model and metrics management - Data upload and exports - Ad-hoc analysis of geospatial data - Full text and geographic search - Configuration of CleverMaps Studio visualizations 

    The version of the OpenAPI document: 1.0.0
    Contact: support@clevermaps.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cm_python_openapi_sdk.models.job_detail_response import JobDetailResponse

class TestJobDetailResponse(unittest.TestCase):
    """JobDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobDetailResponse:
        """Test JobDetailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobDetailResponse`
        """
        model = JobDetailResponse()
        if include_optional:
            return JobDetailResponse(
                id = '0',
                type = '0',
                status = 'RUNNING',
                start_date = 56,
                end_date = 56,
                message = '',
                result = None,
                links = [
                    None
                    ]
            )
        else:
            return JobDetailResponse(
                id = '0',
                type = '0',
                status = 'RUNNING',
        )
        """

    def testJobDetailResponse(self):
        """Test JobDetailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
