# coding: utf-8

"""
    clevermaps-client

    CleverMaps REST API provides access to location intelligence and geospatial analytics platform.  ### Main capabilities include: - Project and user access management - Multidimensional data model and metrics management - Data upload and exports - Ad-hoc analysis of geospatial data - Full text and geographic search - Configuration of CleverMaps Studio visualizations 

    The version of the OpenAPI document: 1.0.0
    Contact: support@clevermaps.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, field_validator
from typing import Optional
from typing_extensions import Annotated
from cm_python_openapi_sdk.models.dwh_query_request1 import DwhQueryRequest1
from cm_python_openapi_sdk.models.queries_response import QueriesResponse
from cm_python_openapi_sdk.models.query_response import QueryResponse

from cm_python_openapi_sdk.api_client import ApiClient, RequestSerialized
from cm_python_openapi_sdk.api_response import ApiResponse
from cm_python_openapi_sdk.rest import RESTResponseType


class QueriesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def accept_queries(
        self,
        project_id: Annotated[str, Field(strict=True, description="Id of the project")],
        dwh_cluster_id: Annotated[str, Field(strict=True, description="Id of the dwh cluster")],
        dwh_query_request1: DwhQueryRequest1,
        size: Annotated[Optional[Annotated[int, Field(le=20000, strict=True, ge=1)]], Field(description="The count of records to return for one page")] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Number of the page")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> QueriesResponse:
        """Accept queries

        Accepts a query to be computed on a data warehouse. This is the main endpoint for computing data messages on a multidimensional data model.  The POST of an query request starts an asynchronous task and returns the location URI of the result in `location` response header. To get the status of asynchronous report result computation, client must make another GET request on the URI from `location` header (see [getQueries](#operation/getQueries)).  More information about functions and building CleverMaps metrics is described in the developer documentation: - [Metric's documentation](https://docs.clevermaps.io/docs/metrics) - [DWH query function list](https://docs.clevermaps.io/docs/metrics#Metrics-DWHqueryfunctionlistDWH-query-function-list) - [Filter operators list ](https://docs.clevermaps.io/docs/metrics#Metrics-FilteroperatorslistFilter-operators-list) - [Metrics cheatsheet](https://docs.clevermaps.io/docs/metrics-cheatsheet) 

        :param project_id: Id of the project (required)
        :type project_id: str
        :param dwh_cluster_id: Id of the dwh cluster (required)
        :type dwh_cluster_id: str
        :param dwh_query_request1: (required)
        :type dwh_query_request1: DwhQueryRequest1
        :param size: The count of records to return for one page
        :type size: int
        :param page: Number of the page
        :type page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._accept_queries_serialize(
            project_id=project_id,
            dwh_cluster_id=dwh_cluster_id,
            dwh_query_request1=dwh_query_request1,
            size=size,
            page=page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "QueriesResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def accept_queries_with_http_info(
        self,
        project_id: Annotated[str, Field(strict=True, description="Id of the project")],
        dwh_cluster_id: Annotated[str, Field(strict=True, description="Id of the dwh cluster")],
        dwh_query_request1: DwhQueryRequest1,
        size: Annotated[Optional[Annotated[int, Field(le=20000, strict=True, ge=1)]], Field(description="The count of records to return for one page")] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Number of the page")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[QueriesResponse]:
        """Accept queries

        Accepts a query to be computed on a data warehouse. This is the main endpoint for computing data messages on a multidimensional data model.  The POST of an query request starts an asynchronous task and returns the location URI of the result in `location` response header. To get the status of asynchronous report result computation, client must make another GET request on the URI from `location` header (see [getQueries](#operation/getQueries)).  More information about functions and building CleverMaps metrics is described in the developer documentation: - [Metric's documentation](https://docs.clevermaps.io/docs/metrics) - [DWH query function list](https://docs.clevermaps.io/docs/metrics#Metrics-DWHqueryfunctionlistDWH-query-function-list) - [Filter operators list ](https://docs.clevermaps.io/docs/metrics#Metrics-FilteroperatorslistFilter-operators-list) - [Metrics cheatsheet](https://docs.clevermaps.io/docs/metrics-cheatsheet) 

        :param project_id: Id of the project (required)
        :type project_id: str
        :param dwh_cluster_id: Id of the dwh cluster (required)
        :type dwh_cluster_id: str
        :param dwh_query_request1: (required)
        :type dwh_query_request1: DwhQueryRequest1
        :param size: The count of records to return for one page
        :type size: int
        :param page: Number of the page
        :type page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._accept_queries_serialize(
            project_id=project_id,
            dwh_cluster_id=dwh_cluster_id,
            dwh_query_request1=dwh_query_request1,
            size=size,
            page=page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "QueriesResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def accept_queries_without_preload_content(
        self,
        project_id: Annotated[str, Field(strict=True, description="Id of the project")],
        dwh_cluster_id: Annotated[str, Field(strict=True, description="Id of the dwh cluster")],
        dwh_query_request1: DwhQueryRequest1,
        size: Annotated[Optional[Annotated[int, Field(le=20000, strict=True, ge=1)]], Field(description="The count of records to return for one page")] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Number of the page")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Accept queries

        Accepts a query to be computed on a data warehouse. This is the main endpoint for computing data messages on a multidimensional data model.  The POST of an query request starts an asynchronous task and returns the location URI of the result in `location` response header. To get the status of asynchronous report result computation, client must make another GET request on the URI from `location` header (see [getQueries](#operation/getQueries)).  More information about functions and building CleverMaps metrics is described in the developer documentation: - [Metric's documentation](https://docs.clevermaps.io/docs/metrics) - [DWH query function list](https://docs.clevermaps.io/docs/metrics#Metrics-DWHqueryfunctionlistDWH-query-function-list) - [Filter operators list ](https://docs.clevermaps.io/docs/metrics#Metrics-FilteroperatorslistFilter-operators-list) - [Metrics cheatsheet](https://docs.clevermaps.io/docs/metrics-cheatsheet) 

        :param project_id: Id of the project (required)
        :type project_id: str
        :param dwh_cluster_id: Id of the dwh cluster (required)
        :type dwh_cluster_id: str
        :param dwh_query_request1: (required)
        :type dwh_query_request1: DwhQueryRequest1
        :param size: The count of records to return for one page
        :type size: int
        :param page: Number of the page
        :type page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._accept_queries_serialize(
            project_id=project_id,
            dwh_cluster_id=dwh_cluster_id,
            dwh_query_request1=dwh_query_request1,
            size=size,
            page=page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "QueriesResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _accept_queries_serialize(
        self,
        project_id,
        dwh_cluster_id,
        dwh_query_request1,
        size,
        page,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if project_id is not None:
            _path_params['projectId'] = project_id
        if dwh_cluster_id is not None:
            _path_params['dwhClusterId'] = dwh_cluster_id
        # process the query parameters
        if size is not None:
            
            _query_params.append(('size', size))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if dwh_query_request1 is not None:
            _body_params = dwh_query_request1


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/projects/{projectId}/dwh/{dwhClusterId}/queries',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_queries(
        self,
        project_id: Annotated[str, Field(strict=True, description="Id of the project")],
        dwh_cluster_id: Annotated[str, Field(strict=True, description="Id of the dwh cluster")],
        dwh_cache_id: Annotated[str, Field(strict=True, description="Id of the dwh cache")],
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Number of the page")] = None,
        size: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="The count of records to return for one page")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> QueryResponse:
        """Get queries

        Get the result of the asynchronous query request submitted in [acceptQueries](#operation/acceptQueries).  This endpoint implements long polling - the client polls the Location URI and the server holds the request open until the query result is available. Then returns either successful or failed response.  It is also possible that the request will time out and respond with 404 after 30s. This can mean two things: * The result is still being computed * The result was not found  In that case, the client can make another request and wait if the result will be computed in another 30s interval. The number of repeated GET requests is up to the client. 

        :param project_id: Id of the project (required)
        :type project_id: str
        :param dwh_cluster_id: Id of the dwh cluster (required)
        :type dwh_cluster_id: str
        :param dwh_cache_id: Id of the dwh cache (required)
        :type dwh_cache_id: str
        :param page: Number of the page
        :type page: int
        :param size: The count of records to return for one page
        :type size: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_queries_serialize(
            project_id=project_id,
            dwh_cluster_id=dwh_cluster_id,
            dwh_cache_id=dwh_cache_id,
            page=page,
            size=size,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QueryResponse",
            '404': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_queries_with_http_info(
        self,
        project_id: Annotated[str, Field(strict=True, description="Id of the project")],
        dwh_cluster_id: Annotated[str, Field(strict=True, description="Id of the dwh cluster")],
        dwh_cache_id: Annotated[str, Field(strict=True, description="Id of the dwh cache")],
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Number of the page")] = None,
        size: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="The count of records to return for one page")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[QueryResponse]:
        """Get queries

        Get the result of the asynchronous query request submitted in [acceptQueries](#operation/acceptQueries).  This endpoint implements long polling - the client polls the Location URI and the server holds the request open until the query result is available. Then returns either successful or failed response.  It is also possible that the request will time out and respond with 404 after 30s. This can mean two things: * The result is still being computed * The result was not found  In that case, the client can make another request and wait if the result will be computed in another 30s interval. The number of repeated GET requests is up to the client. 

        :param project_id: Id of the project (required)
        :type project_id: str
        :param dwh_cluster_id: Id of the dwh cluster (required)
        :type dwh_cluster_id: str
        :param dwh_cache_id: Id of the dwh cache (required)
        :type dwh_cache_id: str
        :param page: Number of the page
        :type page: int
        :param size: The count of records to return for one page
        :type size: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_queries_serialize(
            project_id=project_id,
            dwh_cluster_id=dwh_cluster_id,
            dwh_cache_id=dwh_cache_id,
            page=page,
            size=size,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QueryResponse",
            '404': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_queries_without_preload_content(
        self,
        project_id: Annotated[str, Field(strict=True, description="Id of the project")],
        dwh_cluster_id: Annotated[str, Field(strict=True, description="Id of the dwh cluster")],
        dwh_cache_id: Annotated[str, Field(strict=True, description="Id of the dwh cache")],
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Number of the page")] = None,
        size: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="The count of records to return for one page")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get queries

        Get the result of the asynchronous query request submitted in [acceptQueries](#operation/acceptQueries).  This endpoint implements long polling - the client polls the Location URI and the server holds the request open until the query result is available. Then returns either successful or failed response.  It is also possible that the request will time out and respond with 404 after 30s. This can mean two things: * The result is still being computed * The result was not found  In that case, the client can make another request and wait if the result will be computed in another 30s interval. The number of repeated GET requests is up to the client. 

        :param project_id: Id of the project (required)
        :type project_id: str
        :param dwh_cluster_id: Id of the dwh cluster (required)
        :type dwh_cluster_id: str
        :param dwh_cache_id: Id of the dwh cache (required)
        :type dwh_cache_id: str
        :param page: Number of the page
        :type page: int
        :param size: The count of records to return for one page
        :type size: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_queries_serialize(
            project_id=project_id,
            dwh_cluster_id=dwh_cluster_id,
            dwh_cache_id=dwh_cache_id,
            page=page,
            size=size,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QueryResponse",
            '404': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_queries_serialize(
        self,
        project_id,
        dwh_cluster_id,
        dwh_cache_id,
        page,
        size,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if project_id is not None:
            _path_params['projectId'] = project_id
        if dwh_cluster_id is not None:
            _path_params['dwhClusterId'] = dwh_cluster_id
        if dwh_cache_id is not None:
            _path_params['dwhCacheId'] = dwh_cache_id
        # process the query parameters
        if page is not None:
            
            _query_params.append(('page', page))
            
        if size is not None:
            
            _query_params.append(('size', size))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/projects/{projectId}/dwh/{dwhClusterId}/queries/{dwhCacheId}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


