# coding: utf-8

"""
    clevermaps-client

    CleverMaps REST API provides access to location intelligence and geospatial analytics platform.  ### Main capabilities include: - Project and user access management - Multidimensional data model and metrics management - Data upload and exports - Ad-hoc analysis of geospatial data - Full text and geographic search - Configuration of CleverMaps Studio visualizations 

    The version of the OpenAPI document: 1.0.0
    Contact: support@clevermaps.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cm_python_openapi_sdk.models.double_counting_warnings import DoubleCountingWarnings
from typing import Optional, Set
from typing_extensions import Self

class ExecutionDetail(BaseModel):
    """
    ExecutionDetail
    """ # noqa: E501
    double_counting_warnings: Optional[List[DoubleCountingWarnings]] = Field(default=None, alias="doubleCountingWarnings")
    dwh_query_metric_names: Optional[List[StrictStr]] = Field(default=None, alias="dwhQueryMetricNames")
    feature: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    view_name: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="viewName")
    __properties: ClassVar[List[str]] = ["doubleCountingWarnings", "dwhQueryMetricNames", "feature", "viewName"]

    @field_validator('view_name')
    def view_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z][a-z0-9_-]*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z][a-z0-9_-]*$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExecutionDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in double_counting_warnings (list)
        _items = []
        if self.double_counting_warnings:
            for _item_double_counting_warnings in self.double_counting_warnings:
                if _item_double_counting_warnings:
                    _items.append(_item_double_counting_warnings.to_dict())
            _dict['doubleCountingWarnings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExecutionDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "doubleCountingWarnings": [DoubleCountingWarnings.from_dict(_item) for _item in obj["doubleCountingWarnings"]] if obj.get("doubleCountingWarnings") is not None else None,
            "dwhQueryMetricNames": obj.get("dwhQueryMetricNames"),
            "feature": obj.get("feature"),
            "viewName": obj.get("viewName")
        })
        return _obj


