# coding: utf-8

"""
    clevermaps-client

    CleverMaps REST API provides access to location intelligence and geospatial analytics platform.  ### Main capabilities include: - Project and user access management - Multidimensional data model and metrics management - Data upload and exports - Ad-hoc analysis of geospatial data - Full text and geographic search - Configuration of CleverMaps Studio visualizations 

    The version of the OpenAPI document: 1.0.0
    Contact: support@clevermaps.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from cm_python_openapi_sdk.models.filter_by_comp import FilterByComp
from cm_python_openapi_sdk.models.filter_by_in import FilterByIn
from cm_python_openapi_sdk.models.filter_by_unary import FilterByUnary
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

FILTERBY_ONE_OF_SCHEMAS = ["FilterByAttribute", "FilterByBoolean", "FilterByComp", "FilterByIn", "FilterByUnary"]

class FilterBy(BaseModel):
    """
    FilterBy
    """
    # data type: FilterByComp
    oneof_schema_1_validator: Optional[FilterByComp] = None
    # data type: FilterByIn
    oneof_schema_2_validator: Optional[FilterByIn] = None
    # data type: FilterByAttribute
    oneof_schema_3_validator: Optional[FilterByAttribute] = None
    # data type: FilterByUnary
    oneof_schema_4_validator: Optional[FilterByUnary] = None
    # data type: FilterByBoolean
    oneof_schema_5_validator: Optional[FilterByBoolean] = None
    actual_instance: Optional[Union[FilterByAttribute, FilterByBoolean, FilterByComp, FilterByIn, FilterByUnary]] = None
    one_of_schemas: Set[str] = { "FilterByAttribute", "FilterByBoolean", "FilterByComp", "FilterByIn", "FilterByUnary" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = FilterBy.model_construct()
        error_messages = []
        match = 0
        # validate data type: FilterByComp
        if not isinstance(v, FilterByComp):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FilterByComp`")
        else:
            match += 1
        # validate data type: FilterByIn
        if not isinstance(v, FilterByIn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FilterByIn`")
        else:
            match += 1
        # validate data type: FilterByAttribute
        if not isinstance(v, FilterByAttribute):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FilterByAttribute`")
        else:
            match += 1
        # validate data type: FilterByUnary
        if not isinstance(v, FilterByUnary):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FilterByUnary`")
        else:
            match += 1
        # validate data type: FilterByBoolean
        if not isinstance(v, FilterByBoolean):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FilterByBoolean`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in FilterBy with oneOf schemas: FilterByAttribute, FilterByBoolean, FilterByComp, FilterByIn, FilterByUnary. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in FilterBy with oneOf schemas: FilterByAttribute, FilterByBoolean, FilterByComp, FilterByIn, FilterByUnary. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # use oneOf discriminator to lookup the data type
        _data_type = json.loads(json_str).get("operator")
        if not _data_type:
            raise ValueError("Failed to lookup data type from the field `operator` in the input.")

        # check if data type is `FilterByBoolean`
        if _data_type == "and":
            instance.actual_instance = FilterByBoolean.from_json(json_str)
            return instance

        # check if data type is `FilterByComp`
        if _data_type == "eq":
            instance.actual_instance = FilterByComp.from_json(json_str)
            return instance

        # check if data type is `FilterByComp`
        if _data_type == "gt":
            instance.actual_instance = FilterByComp.from_json(json_str)
            return instance

        # check if data type is `FilterByComp`
        if _data_type == "gte":
            instance.actual_instance = FilterByComp.from_json(json_str)
            return instance

        # check if data type is `FilterByIn`
        if _data_type == "in":
            instance.actual_instance = FilterByIn.from_json(json_str)
            return instance

        # check if data type is `FilterByAttribute`
        if _data_type == "inAttribute":
            instance.actual_instance = FilterByAttribute.from_json(json_str)
            return instance

        # check if data type is `FilterByUnary`
        if _data_type == "isNotNull":
            instance.actual_instance = FilterByUnary.from_json(json_str)
            return instance

        # check if data type is `FilterByUnary`
        if _data_type == "isNull":
            instance.actual_instance = FilterByUnary.from_json(json_str)
            return instance

        # check if data type is `FilterByComp`
        if _data_type == "lt":
            instance.actual_instance = FilterByComp.from_json(json_str)
            return instance

        # check if data type is `FilterByComp`
        if _data_type == "lte":
            instance.actual_instance = FilterByComp.from_json(json_str)
            return instance

        # check if data type is `FilterByComp`
        if _data_type == "ne":
            instance.actual_instance = FilterByComp.from_json(json_str)
            return instance

        # check if data type is `FilterByBoolean`
        if _data_type == "not":
            instance.actual_instance = FilterByBoolean.from_json(json_str)
            return instance

        # check if data type is `FilterByAttribute`
        if _data_type == "notInAttribute":
            instance.actual_instance = FilterByAttribute.from_json(json_str)
            return instance

        # check if data type is `FilterByBoolean`
        if _data_type == "or":
            instance.actual_instance = FilterByBoolean.from_json(json_str)
            return instance

        # check if data type is `FilterByAttribute`
        if _data_type == "FilterByAttribute":
            instance.actual_instance = FilterByAttribute.from_json(json_str)
            return instance

        # check if data type is `FilterByBoolean`
        if _data_type == "FilterByBoolean":
            instance.actual_instance = FilterByBoolean.from_json(json_str)
            return instance

        # check if data type is `FilterByComp`
        if _data_type == "FilterByComp":
            instance.actual_instance = FilterByComp.from_json(json_str)
            return instance

        # check if data type is `FilterByIn`
        if _data_type == "FilterByIn":
            instance.actual_instance = FilterByIn.from_json(json_str)
            return instance

        # check if data type is `FilterByUnary`
        if _data_type == "FilterByUnary":
            instance.actual_instance = FilterByUnary.from_json(json_str)
            return instance

        # deserialize data into FilterByComp
        try:
            instance.actual_instance = FilterByComp.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FilterByIn
        try:
            instance.actual_instance = FilterByIn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FilterByAttribute
        try:
            instance.actual_instance = FilterByAttribute.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FilterByUnary
        try:
            instance.actual_instance = FilterByUnary.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FilterByBoolean
        try:
            instance.actual_instance = FilterByBoolean.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into FilterBy with oneOf schemas: FilterByAttribute, FilterByBoolean, FilterByComp, FilterByIn, FilterByUnary. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into FilterBy with oneOf schemas: FilterByAttribute, FilterByBoolean, FilterByComp, FilterByIn, FilterByUnary. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FilterByAttribute, FilterByBoolean, FilterByComp, FilterByIn, FilterByUnary]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from cm_python_openapi_sdk.models.filter_by_attribute import FilterByAttribute
from cm_python_openapi_sdk.models.filter_by_boolean import FilterByBoolean
# TODO: Rewrite to not use raise_errors
FilterBy.model_rebuild(raise_errors=False)

